### ISSUE TITLE
خطأ كتابي في صفحة readme

### ISSUE THREAD

**Issue by loaialaddien** [KL13NT/arabic-a11y#5]
<div dir="rtl">
 السطر ده 

>  ما يقدّر بـ 28 شخص في إقليم شرق المتوسط،

 المفروض يبقي 

>  ما يقدّر بـ 28 مليون شخص في إقليم شرق المتوسط

</div>

**Comment by KL13NT** [comment]
<div dir="rtl">

اهلاً بيك! اشكرك على مساهمتك دي واتمنى نشوفك تاني في مساهمات اخرى :smiley: 

تحب تعمل PR تصلح الخطأ ده فيها ولا اعدلها انا و اعملك منشن في الـ `commit message`؟ 

</div>

**Comment by loaialaddien** [comment]
I created the PR
