### ISSUE TITLE
adding notable current projects that enrich Arabic content online

### ISSUE THREAD

**Issue by loaialaddien** [KL13NT/arabic-a11y#9]
<div dir="rtl">
 ممكن نضيف سكشن في ملف ال readme بيعمل اضاءة علي المشاريع المختلفة الي بتضيف للمحتوي العربى 
زي الموقع ده مثلا 

https://github.com/javascript-tutorial/ar.javascript.info/tree/master</a>
https://ar.javascript.info/
</div>

**Comment by KL13NT** [comment]
<div dir="rtl">

> 
> ممكن نضيف سكشن في ملف ال readme بيعمل اضاءة علي المشاريع المختلفة الي بتضيف للمحتوي العربى زي الموقع ده مثلا
> 
> https://github.com/javascript-tutorial/ar.javascript.info/tree/master
> https://ar.javascript.info/

مساهمتين في يوم واحد, ايه الجمال :smiley: 
فكرة جميلة و اكيد لازم نعمل كده, تحب تبدأ انت القسم ده في الـ README؟ 

</div>

**Comment by loaialaddien** [comment]
<div dir="rtl">
انت ممكت تبدأه و انا هبقي افتح PR كل لما الاقي حاجه
</div>

**Comment by KL13NT** [comment]
<div dir="rtl">

تم. موجود دلوقتي ملف بإسم Notable Projects هنجمع فيه المشاريع دي بأساميها و وصف صغير و رابط للمشاريع. 


</div>
